# Libreria Numpy

**Numpy** es el paquete más básico pero poderoso para la computación científica y la manipulación de datos en Python. Nos permite trabajar con matrices y matrices multidimensionales.

Entre sus funciones estan:
* Matrices n-dimensionales.
* Funciones sofisticadas (como codigos de radiodifusión).
* Es capaz de integrarse con otros lenguajes tales como C/C++, Fortran y R.

Mail para consultas: damiansilva14@hotmail.com


## Importamos las librerias

In [1]:
import numpy as np

La libreria de numpy tiene como principales estructuras de datos a los **vectores**, las **matrices** y a los **arrays**

### Matrices
Una matriz es un conjunto de datos rectangulares bidimensionales. 

### Arrays
Mientras que las matrices se limitan a dos dimensiones, las arrays pueden ser de cualquier número
de dimensiones. 


Comencemos con un vector

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [8]:
a = np.array([1,2,3,4,5],dtype=np.float64)
a

array([1., 2., 3., 4., 5.])

Al fijar al tipo de dato como float, estamos incluyendo a las decimales

Pero un array no solamente puede contener números dentro de si mismo, sino también palabras e inclusive otras estructuras de datos tales como las listas. 

In [5]:
#Veamos un ejemplo
reca = np.array([(1,(2.0,3.0),'hey'),(2,(3.5,4.0),'n')]
                )

In [6]:
reca

array([[1, (2.0, 3.0), 'hey'],
       [2, (3.5, 4.0), 'n']], dtype=object)

Para observar el primer elemento de este array


In [7]:
reca[0]

array([1, (2.0, 3.0), 'hey'], dtype=object)

Pero enfoquemosnos en el primer objeto (la matrix *a*) \
Para ver la dimensión de este objeto, que nos devolvera la cantidad de columnas:

In [9]:
a.ndim

1

Para ver la forma de este vector, nos devolvera la cantidad de filas:

In [10]:
a.shape

(5,)

Para el producto de este array, que en este caso sera la suma de los componentes de la fila:

In [11]:
a.size

5

In [14]:
#Otro ejemplo
x = np.zeros((3, 5, 2), dtype=np.complex128)
x.size

30

**Numpy** a su vez, nos permite ver las tres cosas juntas en un formato matricial

In [12]:
a.ndim, a.shape, a.size

(1, (5,), 5)

**Continuemos con otro ejemplo de array**

In [15]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float64)
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [16]:
#Veamos el tipo de dato
b.dtype

dtype('float64')

In [17]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

**Ahora formamos un array de ceros**


In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.empty((4,4),dtype = int)

array([[      0,       0,       0,       0],
       [      0,       0,       0,       0],
       [      0,       0,    1156,       0],
       [      0, 2097273,       0, 7274573]])

La funcion `` np.empty ``crea un array del tamaño y tipo de dato especificado (si no se especifica, el tipo será float por defecto) reservando el espacio necesario en memoria para él. Lo más importante a tener en cuenta es que no inicializa el array, es decir, el valor de sus elementos es indeterminado al contener "valores basura". 
Es una buena practica decir que tipo de datos vamos a declarar

In [22]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

La función ``numpy.linspace`` genera un array NumPy formado por n números equiespaciados entre dos dados. Su sintaxis es:**

*numpy.linspace(valor-inicial, valor-final, número de valores)* 

In [23]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

Otra función que nos permite crear un array NumPy es ``numpy.arange``. Al igual que la función predefinida de Python range, genera un conjunto de números entre un valor de inicio y uno final, pudiendo especificar un incremento entre los valores, pero, al contrario de lo que ocurre con range, el resultado aquí es un array NumPy:

In [24]:
np.random.standard_normal((2,4))

array([[-1.8246971 ,  0.45269688,  0.96707838,  0.72571628],
       [ 0.84987756,  1.3500991 , -0.20168539,  0.57722844]])

In [25]:
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))

np.vstack([a,b])

array([[-0.57278366,  1.40344856, -0.75014272],
       [-1.4358726 , -2.11376278, -0.65163351],
       [ 0.4682611 , -0.31367736,  0.13108122],
       [ 0.85114968,  0.54181699, -1.68029573]])

In [26]:
np.hstack([a,b])

array([[-0.57278366,  1.40344856, -0.75014272,  0.4682611 , -0.31367736,
         0.13108122],
       [-1.4358726 , -2.11376278, -0.65163351,  0.85114968,  0.54181699,
        -1.68029573]])

**Para transponer una matriz/array en numpy**

In [ ]:
a.transpose()

# Operaciones Matematicas con Numpy

Las funciones matemáticas básicas funcionan de manera **elementwise** en arrays, y están disponibles como sobrecargas del operador y como funciones en el módulo numpy:

In [1]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print("El array X es:")
print(x)
print()

print("El array Y es:")
print(y)
print()

print(x + y)
print()
print(np.add(x, y))

El array X es:
[[1. 2.]
 [3. 4.]]

El array Y es:
[[5. 6.]
 [7. 8.]]

[[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]


In [2]:
print(x - y)
print()
#Otra manera de ejecutar una resta
print(np.subtract(x, y))


[[-4. -4.]
 [-4. -4.]]

[[-4. -4.]
 [-4. -4.]]


In [3]:
print(x * y)
print()
#Otra manera de multiplicación
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]

[[ 5. 12.]
 [21. 32.]]


In [4]:
print(x / y)
print()
#Otra manera de división
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [6]:
#Raiz Cuadrada
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]



Tenga en cuenta que a diferencia de MATLAB, * es multiplicación elemental, no multiplicación matricial. Utilizamos la función de punto para calcular productos internos de vectores, multiplicar un vector por una matriz y multiplicar matrices. Dot está disponible tanto como una función en el módulo numpy como un método de instancia de objetos de matriz:



In [7]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Producto interno de vectores
print(v.dot(w))
print(np.dot(v, w))

219
219


In [8]:
# Producto de matrices por vectores 
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [9]:
# Multiplicacion de matrices 
print(x.dot(y))
print(np.dot(x, y))


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy proporciona muchas funciones útiles para realizar cálculos en matrices; Uno de los más útiles es **sum**:

In [10]:
x = np.array([[1,2],[3,4]])
print(x)
print()
print (np.sum(x))  # Halla la suma de todos los elementos
print()
print (np.sum(x, axis=0))  # Halla la suma de cada columna
print()
print (np.sum(x, axis=1))  # Halla la suma de cada fila

[[1 2]
 [3 4]]

10

[4 6]

[3 7]


# **Reshape**
Con np.arange() es posible crear "vectores" cuyos elementos tomen valores consecutivos o equiespaciados, como hemos visto anteriormente. ¿Podemos hacer lo mismo con "matrices"? Pues sí, pero no usando una sola función. Imagina que quieres crear algo como esto:

$$
\left(\begin{array}{ccc} 
10 ; 20 ; 30\\
40 ; 50 ; 60\\
70 ; 80 ; 90\\
\end{array}\right)
$$
* Comenzaremos por crear un array 1d con los valores (10,20,30,40...) usando np.arange().
* Luego le daremos forma de array 2d. con np.reshape(array, (dim0, dim1)).

In [11]:
a = np.arange(10,100,10)
print(a)
print()

M = np.reshape(a, [3, 3])
print(M)

[10 20 30 40 50 60 70 80 90]

[[10 20 30]
 [40 50 60]
 [70 80 90]]


# Broadcasting
**Broadcasting** es un potente mecanismo que permite a numpy trabajar con matrices de diferentes formas al realizar operaciones aritméticas. Con frecuencia tenemos una matriz más pequeña y una matriz más grande, y queremos usar la matriz más pequeña varias veces para realizar alguna operación en la matriz más grande.



![](https://claudiovz.github.io/scipy-lecture-notes-ES/_images/numpy_broadcasting.png)

In [12]:
import numpy as np

# Vamos a añadir el vector V a cada fila de la matriz x
# guardando el resultado en la matriz y

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Creamos una matriz vacia de la misma forma de X

# Añadimos el vector v a cada fila de la matriz X con un loop

for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Esto funciona; Sin embargo, cuando la matriz x es muy grande, el cálculo de un bucle explícito en Python podría ser lento. Obsérvese que la adición del vector v a cada fila de la matriz x es equivalente a formar una matriz vv apilando múltiples copias de v verticalmente, realizando entonces la suma elemental de x y vv. Podríamos implementar este enfoque como este:

Numpy Broadcasting nos permite realizar este cálculo sin realmente crear múltiples copias de v. Considere esta versión, utilizando la Broadcasting:

In [13]:
import numpy as np

# Vamos a añadir el vector V a cada fila de la matriz x
# guardando el resultado en la matriz y

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Añada v a cada fila de x mediante broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
